spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;IGNORECASE=true;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        type: TRACE
        format_sql: true
        show_sql: true
        use_sql_comments: true

    defer-datasource-initialization: false
    show-sql: true



  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

